baseurl = "http://ciscopema.com/"
languageCode = "en-us"
title = "Cisco Pema"
author = "Tomas Hayes"
theme = "hugo-cisco" #"hugo-uno"


[Params]  # For hugo-uno
description = "New Album Release June 2016"
description_link = "http://www.youtube.com/embed/LaM6oSp1M00"
video_id = "LaM6oSp1M00"
cover = "/images/cd-cover.jpg"
email = "hola@ciscopema.com"
instagram = "ciscopema"
facebook = "ciscopemamusic"
youtube = "https://www.youtube.com/channel/UC3K26naF-NtGUZzu-Mrb2Sw"
