baseurl = "http://ciscopema.com/"
languageCode = "en-us"
title = "Cisco Pema"
author = "Tomas Hayes"
theme = "hugo-cisco" #"hugo-uno"


[Params]  # For hugo-uno
description = "New Album Release October 2016"
description_link = "http://www.youtube.com/embed/x8ErOxGPiGY"
video_id = "x8ErOxGPiGY"
cover = "/images/cd-cover.jpg"
email = "hola@ciscopema.com"
instagram = "ciscopema"
facebook = "ciscopemamusic"
youtube = "channel/UC3K26naF-NtGUZzu-Mrb2Sw"
youtube_title = 'Youtube channel'
